package com.dzmsoft.oim.finance.dao;

import com.dzmsoft.oim.finance.pojo.OimPaymentBill;
import com.dzmsoft.oim.finance.pojo.OimPaymentBillExample;
import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface OimPaymentBillMapper {
    public PageList<OimPaymentBill> selectByExample(OimPaymentBillExample example,PageBounds pageBounds);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_payment_bill
     *
     * @mbggenerated Tue Jun 28 23:39:20 CST 2016
     */
    int countByExample(OimPaymentBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_payment_bill
     *
     * @mbggenerated Tue Jun 28 23:39:20 CST 2016
     */
    int deleteByExample(OimPaymentBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_payment_bill
     *
     * @mbggenerated Tue Jun 28 23:39:20 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_payment_bill
     *
     * @mbggenerated Tue Jun 28 23:39:20 CST 2016
     */
    int insert(OimPaymentBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_payment_bill
     *
     * @mbggenerated Tue Jun 28 23:39:20 CST 2016
     */
    int insertSelective(OimPaymentBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_payment_bill
     *
     * @mbggenerated Tue Jun 28 23:39:20 CST 2016
     */
    List<OimPaymentBill> selectByExample(OimPaymentBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_payment_bill
     *
     * @mbggenerated Tue Jun 28 23:39:20 CST 2016
     */
    OimPaymentBill selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_payment_bill
     *
     * @mbggenerated Tue Jun 28 23:39:20 CST 2016
     */
    int updateByExampleSelective(@Param("record") OimPaymentBill record, @Param("example") OimPaymentBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_payment_bill
     *
     * @mbggenerated Tue Jun 28 23:39:20 CST 2016
     */
    int updateByExample(@Param("record") OimPaymentBill record, @Param("example") OimPaymentBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_payment_bill
     *
     * @mbggenerated Tue Jun 28 23:39:20 CST 2016
     */
    int updateByPrimaryKeySelective(OimPaymentBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_payment_bill
     *
     * @mbggenerated Tue Jun 28 23:39:20 CST 2016
     */
    int updateByPrimaryKey(OimPaymentBill record);
}