package com.dzmsoft.oim.finance.dao;

import com.dzmsoft.oim.finance.pojo.OimRecipientBill;
import com.dzmsoft.oim.finance.pojo.OimRecipientBillExample;
import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface OimRecipientBillMapper {
    
    public PageList<OimRecipientBill> selectByExample(OimRecipientBillExample example,PageBounds pageBounds);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_recipient_bill
     *
     * @mbggenerated Tue Jun 28 23:39:20 CST 2016
     */
    int countByExample(OimRecipientBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_recipient_bill
     *
     * @mbggenerated Tue Jun 28 23:39:20 CST 2016
     */
    int deleteByExample(OimRecipientBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_recipient_bill
     *
     * @mbggenerated Tue Jun 28 23:39:20 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_recipient_bill
     *
     * @mbggenerated Tue Jun 28 23:39:20 CST 2016
     */
    int insert(OimRecipientBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_recipient_bill
     *
     * @mbggenerated Tue Jun 28 23:39:20 CST 2016
     */
    int insertSelective(OimRecipientBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_recipient_bill
     *
     * @mbggenerated Tue Jun 28 23:39:20 CST 2016
     */
    List<OimRecipientBill> selectByExample(OimRecipientBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_recipient_bill
     *
     * @mbggenerated Tue Jun 28 23:39:20 CST 2016
     */
    OimRecipientBill selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_recipient_bill
     *
     * @mbggenerated Tue Jun 28 23:39:20 CST 2016
     */
    int updateByExampleSelective(@Param("record") OimRecipientBill record, @Param("example") OimRecipientBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_recipient_bill
     *
     * @mbggenerated Tue Jun 28 23:39:20 CST 2016
     */
    int updateByExample(@Param("record") OimRecipientBill record, @Param("example") OimRecipientBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_recipient_bill
     *
     * @mbggenerated Tue Jun 28 23:39:20 CST 2016
     */
    int updateByPrimaryKeySelective(OimRecipientBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_recipient_bill
     *
     * @mbggenerated Tue Jun 28 23:39:20 CST 2016
     */
    int updateByPrimaryKey(OimRecipientBill record);
}