package com.dzmsoft.oim.base.dao;

import com.dzmsoft.oim.base.pojo.OimAdRegion;
import com.dzmsoft.oim.base.pojo.OimAdRegionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OimAdRegionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_ad_region
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    int countByExample(OimAdRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_ad_region
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    int deleteByExample(OimAdRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_ad_region
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_ad_region
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    int insert(OimAdRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_ad_region
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    int insertSelective(OimAdRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_ad_region
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    List<OimAdRegion> selectByExample(OimAdRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_ad_region
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    OimAdRegion selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_ad_region
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    int updateByExampleSelective(@Param("record") OimAdRegion record, @Param("example") OimAdRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_ad_region
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    int updateByExample(@Param("record") OimAdRegion record, @Param("example") OimAdRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_ad_region
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    int updateByPrimaryKeySelective(OimAdRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_ad_region
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    int updateByPrimaryKey(OimAdRegion record);
}