package com.dzmsoft.oim.base.dao;

import com.dzmsoft.oim.base.pojo.OimAdPosition;
import com.dzmsoft.oim.base.pojo.OimAdPositionExample;
import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface OimAdPositionMapper {
    public PageList<OimAdPosition> selectByExample(OimAdPositionExample example,PageBounds pageBounds);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_ad_position
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    int countByExample(OimAdPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_ad_position
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    int deleteByExample(OimAdPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_ad_position
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_ad_position
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    int insert(OimAdPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_ad_position
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    int insertSelective(OimAdPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_ad_position
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    List<OimAdPosition> selectByExample(OimAdPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_ad_position
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    OimAdPosition selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_ad_position
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    int updateByExampleSelective(@Param("record") OimAdPosition record, @Param("example") OimAdPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_ad_position
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    int updateByExample(@Param("record") OimAdPosition record, @Param("example") OimAdPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_ad_position
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    int updateByPrimaryKeySelective(OimAdPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_ad_position
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    int updateByPrimaryKey(OimAdPosition record);
}