package com.dzmsoft.oim.base.dao;

import com.dzmsoft.oim.base.pojo.OimApk;
import com.dzmsoft.oim.base.pojo.OimApkExample;
import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface OimApkMapper {
    public PageList<OimApk> selectByExample(OimApkExample example,PageBounds pageBounds);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_apk
     *
     * @mbggenerated Wed May 04 13:23:16 CST 2016
     */
    int countByExample(OimApkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_apk
     *
     * @mbggenerated Wed May 04 13:23:16 CST 2016
     */
    int deleteByExample(OimApkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_apk
     *
     * @mbggenerated Wed May 04 13:23:16 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_apk
     *
     * @mbggenerated Wed May 04 13:23:16 CST 2016
     */
    int insert(OimApk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_apk
     *
     * @mbggenerated Wed May 04 13:23:16 CST 2016
     */
    int insertSelective(OimApk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_apk
     *
     * @mbggenerated Wed May 04 13:23:16 CST 2016
     */
    List<OimApk> selectByExample(OimApkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_apk
     *
     * @mbggenerated Wed May 04 13:23:16 CST 2016
     */
    OimApk selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_apk
     *
     * @mbggenerated Wed May 04 13:23:16 CST 2016
     */
    int updateByExampleSelective(@Param("record") OimApk record, @Param("example") OimApkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_apk
     *
     * @mbggenerated Wed May 04 13:23:16 CST 2016
     */
    int updateByExample(@Param("record") OimApk record, @Param("example") OimApkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_apk
     *
     * @mbggenerated Wed May 04 13:23:16 CST 2016
     */
    int updateByPrimaryKeySelective(OimApk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_apk
     *
     * @mbggenerated Wed May 04 13:23:16 CST 2016
     */
    int updateByPrimaryKey(OimApk record);
}