package com.dzmsoft.oim.base.dao;

import com.dzmsoft.oim.base.pojo.OimAdArticle;
import com.dzmsoft.oim.base.pojo.OimAdArticleExample;
import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface OimAdArticleMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_ad_article
     * @mbggenerated  Wed Apr 27 13:12:04 CST 2016
     */
    int countByExample(OimAdArticleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_ad_article
     * @mbggenerated  Wed Apr 27 13:12:04 CST 2016
     */
    int deleteByExample(OimAdArticleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_ad_article
     * @mbggenerated  Wed Apr 27 13:12:04 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_ad_article
     * @mbggenerated  Wed Apr 27 13:12:04 CST 2016
     */
    int insert(OimAdArticle record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_ad_article
     * @mbggenerated  Wed Apr 27 13:12:04 CST 2016
     */
    int insertSelective(OimAdArticle record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_ad_article
     * @mbggenerated  Wed Apr 27 13:12:04 CST 2016
     */
    List<OimAdArticle> selectByExampleWithBLOBs(OimAdArticleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_ad_article
     * @mbggenerated  Wed Apr 27 13:12:04 CST 2016
     */
    List<OimAdArticle> selectByExample(OimAdArticleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_ad_article
     * @mbggenerated  Wed Apr 27 13:12:04 CST 2016
     */
    OimAdArticle selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_ad_article
     * @mbggenerated  Wed Apr 27 13:12:04 CST 2016
     */
    int updateByExampleSelective(@Param("record") OimAdArticle record,
            @Param("example") OimAdArticleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_ad_article
     * @mbggenerated  Wed Apr 27 13:12:04 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") OimAdArticle record,
            @Param("example") OimAdArticleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_ad_article
     * @mbggenerated  Wed Apr 27 13:12:04 CST 2016
     */
    int updateByExample(@Param("record") OimAdArticle record,
            @Param("example") OimAdArticleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_ad_article
     * @mbggenerated  Wed Apr 27 13:12:04 CST 2016
     */
    int updateByPrimaryKeySelective(OimAdArticle record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_ad_article
     * @mbggenerated  Wed Apr 27 13:12:04 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(OimAdArticle record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_ad_article
     * @mbggenerated  Wed Apr 27 13:12:04 CST 2016
     */
    int updateByPrimaryKey(OimAdArticle record);

    public PageList<OimAdArticle> selectByExample(OimAdArticleExample example,PageBounds pageBounds);
}