package com.dzmsoft.oim.base.dao;

import com.dzmsoft.oim.base.dto.OperateCityDto;
import com.dzmsoft.oim.base.pojo.OimAdminRegion;
import com.dzmsoft.oim.base.pojo.OimAdminRegionExample;
import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface OimAdminRegionMapper {
    
    public PageList<OimAdminRegion> selectByExample(OimAdminRegionExample example,PageBounds pageBounds);
    
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_admin_region
     * @mbggenerated  Tue Jun 28 12:45:25 CST 2016
     */
    int countByExample(OimAdminRegionExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_admin_region
     * @mbggenerated  Tue Jun 28 12:45:25 CST 2016
     */
    int deleteByExample(OimAdminRegionExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_admin_region
     * @mbggenerated  Tue Jun 28 12:45:25 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_admin_region
     * @mbggenerated  Tue Jun 28 12:45:25 CST 2016
     */
    int insert(OimAdminRegion record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_admin_region
     * @mbggenerated  Tue Jun 28 12:45:25 CST 2016
     */
    int insertSelective(OimAdminRegion record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_admin_region
     * @mbggenerated  Tue Jun 28 12:45:25 CST 2016
     */
    List<OimAdminRegion> selectByExample(OimAdminRegionExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_admin_region
     * @mbggenerated  Tue Jun 28 12:45:25 CST 2016
     */
    OimAdminRegion selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_admin_region
     * @mbggenerated  Tue Jun 28 12:45:25 CST 2016
     */
    int updateByExampleSelective(@Param("record") OimAdminRegion record,
            @Param("example") OimAdminRegionExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_admin_region
     * @mbggenerated  Tue Jun 28 12:45:25 CST 2016
     */
    int updateByExample(@Param("record") OimAdminRegion record,
            @Param("example") OimAdminRegionExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_admin_region
     * @mbggenerated  Tue Jun 28 12:45:25 CST 2016
     */
    int updateByPrimaryKeySelective(OimAdminRegion record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_admin_region
     * @mbggenerated  Tue Jun 28 12:45:25 CST 2016
     */
    int updateByPrimaryKey(OimAdminRegion record);

    /**
     * 根据供应商，获取运营城市
     * @return
     */
    List<OperateCityDto> selectOperateCityDto();
    /**
     * 分页查询运营城市
     * @param pageBounds
     * @return
     */
    PageList<OperateCityDto> selectOperateCityDto(PageBounds pageBounds);
    
}