package com.dzmsoft.oim.base.dao;

import com.dzmsoft.oim.base.pojo.OimCard;
import com.dzmsoft.oim.base.pojo.OimCardExample;
import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface OimCardMapper {
    public PageList<OimCard> selectByExample(OimCardExample example,PageBounds pageBounds);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_card
     *
     * @mbggenerated Tue Jun 28 13:19:02 CST 2016
     */
    int countByExample(OimCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_card
     *
     * @mbggenerated Tue Jun 28 13:19:02 CST 2016
     */
    int deleteByExample(OimCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_card
     *
     * @mbggenerated Tue Jun 28 13:19:02 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_card
     *
     * @mbggenerated Tue Jun 28 13:19:02 CST 2016
     */
    int insert(OimCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_card
     *
     * @mbggenerated Tue Jun 28 13:19:02 CST 2016
     */
    int insertSelective(OimCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_card
     *
     * @mbggenerated Tue Jun 28 13:19:02 CST 2016
     */
    List<OimCard> selectByExampleWithBLOBs(OimCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_card
     *
     * @mbggenerated Tue Jun 28 13:19:02 CST 2016
     */
    List<OimCard> selectByExample(OimCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_card
     *
     * @mbggenerated Tue Jun 28 13:19:02 CST 2016
     */
    OimCard selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_card
     *
     * @mbggenerated Tue Jun 28 13:19:02 CST 2016
     */
    int updateByExampleSelective(@Param("record") OimCard record, @Param("example") OimCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_card
     *
     * @mbggenerated Tue Jun 28 13:19:02 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") OimCard record, @Param("example") OimCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_card
     *
     * @mbggenerated Tue Jun 28 13:19:02 CST 2016
     */
    int updateByExample(@Param("record") OimCard record, @Param("example") OimCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_card
     *
     * @mbggenerated Tue Jun 28 13:19:02 CST 2016
     */
    int updateByPrimaryKeySelective(OimCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_card
     *
     * @mbggenerated Tue Jun 28 13:19:02 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(OimCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_card
     *
     * @mbggenerated Tue Jun 28 13:19:02 CST 2016
     */
    int updateByPrimaryKey(OimCard record);
}