package com.dzmsoft.oim.base.dao;

import com.dzmsoft.oim.base.pojo.OimEmployee;
import com.dzmsoft.oim.base.pojo.OimEmployeeExample;
import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface OimEmployeeMapper {
    
    String selectTopIndex(OimEmployeeExample example);
    
    public PageList<OimEmployee> selectByExample(OimEmployeeExample example,PageBounds pageBounds);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_employee
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    int countByExample(OimEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_employee
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    int deleteByExample(OimEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_employee
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_employee
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    int insert(OimEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_employee
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    int insertSelective(OimEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_employee
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    List<OimEmployee> selectByExample(OimEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_employee
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    OimEmployee selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_employee
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    int updateByExampleSelective(@Param("record") OimEmployee record, @Param("example") OimEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_employee
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    int updateByExample(@Param("record") OimEmployee record, @Param("example") OimEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_employee
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    int updateByPrimaryKeySelective(OimEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_employee
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    int updateByPrimaryKey(OimEmployee record);
}