package com.dzmsoft.oim.base.dao;

import com.dzmsoft.oim.base.pojo.OimHouseholdPriceRule;
import com.dzmsoft.oim.base.pojo.OimHouseholdPriceRuleExample;
import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface OimHouseholdPriceRuleMapper {
    
    public PageList<OimHouseholdPriceRule> selectByExample(OimHouseholdPriceRuleExample example,PageBounds pageBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_household_price_rule
     * @mbggenerated  Tue Jun 28 13:16:00 CST 2016
     */
    int countByExample(OimHouseholdPriceRuleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_household_price_rule
     * @mbggenerated  Tue Jun 28 13:16:00 CST 2016
     */
    int deleteByExample(OimHouseholdPriceRuleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_household_price_rule
     * @mbggenerated  Tue Jun 28 13:16:00 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_household_price_rule
     * @mbggenerated  Tue Jun 28 13:16:00 CST 2016
     */
    int insert(OimHouseholdPriceRule record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_household_price_rule
     * @mbggenerated  Tue Jun 28 13:16:00 CST 2016
     */
    int insertSelective(OimHouseholdPriceRule record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_household_price_rule
     * @mbggenerated  Tue Jun 28 13:16:00 CST 2016
     */
    List<OimHouseholdPriceRule> selectByExampleWithBLOBs(OimHouseholdPriceRuleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_household_price_rule
     * @mbggenerated  Tue Jun 28 13:16:00 CST 2016
     */
    List<OimHouseholdPriceRule> selectByExample(OimHouseholdPriceRuleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_household_price_rule
     * @mbggenerated  Tue Jun 28 13:16:00 CST 2016
     */
    OimHouseholdPriceRule selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_household_price_rule
     * @mbggenerated  Tue Jun 28 13:16:00 CST 2016
     */
    int updateByExampleSelective(@Param("record") OimHouseholdPriceRule record,
            @Param("example") OimHouseholdPriceRuleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_household_price_rule
     * @mbggenerated  Tue Jun 28 13:16:00 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") OimHouseholdPriceRule record,
            @Param("example") OimHouseholdPriceRuleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_household_price_rule
     * @mbggenerated  Tue Jun 28 13:16:00 CST 2016
     */
    int updateByExample(@Param("record") OimHouseholdPriceRule record,
            @Param("example") OimHouseholdPriceRuleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_household_price_rule
     * @mbggenerated  Tue Jun 28 13:16:00 CST 2016
     */
    int updateByPrimaryKeySelective(OimHouseholdPriceRule record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_household_price_rule
     * @mbggenerated  Tue Jun 28 13:16:00 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(OimHouseholdPriceRule record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_household_price_rule
     * @mbggenerated  Tue Jun 28 13:16:00 CST 2016
     */
    int updateByPrimaryKey(OimHouseholdPriceRule record);
}