package com.dzmsoft.oim.base.dao;

import com.dzmsoft.oim.base.pojo.OimMemberAddress;
import com.dzmsoft.oim.base.pojo.OimMemberAddressExample;
import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface OimMemberAddressMapper {
    public PageList<OimMemberAddress> selectByExample(OimMemberAddressExample example,PageBounds pageBounds);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_member_address
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    int countByExample(OimMemberAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_member_address
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    int deleteByExample(OimMemberAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_member_address
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_member_address
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    int insert(OimMemberAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_member_address
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    int insertSelective(OimMemberAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_member_address
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    List<OimMemberAddress> selectByExample(OimMemberAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_member_address
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    OimMemberAddress selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_member_address
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    int updateByExampleSelective(@Param("record") OimMemberAddress record, @Param("example") OimMemberAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_member_address
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    int updateByExample(@Param("record") OimMemberAddress record, @Param("example") OimMemberAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_member_address
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    int updateByPrimaryKeySelective(OimMemberAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_member_address
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    int updateByPrimaryKey(OimMemberAddress record);
}