package com.dzmsoft.oim.base.dao;

import com.dzmsoft.oim.base.pojo.OimMember;
import com.dzmsoft.oim.base.pojo.OimMemberExample;
import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface OimMemberMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_member
     * @mbggenerated  Sat May 21 14:28:55 CST 2016
     */
    int countByExample(OimMemberExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_member
     * @mbggenerated  Sat May 21 14:28:55 CST 2016
     */
    int deleteByExample(OimMemberExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_member
     * @mbggenerated  Sat May 21 14:28:55 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_member
     * @mbggenerated  Sat May 21 14:28:55 CST 2016
     */
    int insert(OimMember record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_member
     * @mbggenerated  Sat May 21 14:28:55 CST 2016
     */
    int insertSelective(OimMember record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_member
     * @mbggenerated  Sat May 21 14:28:55 CST 2016
     */
    List<OimMember> selectByExample(OimMemberExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_member
     * @mbggenerated  Sat May 21 14:28:55 CST 2016
     */
    OimMember selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_member
     * @mbggenerated  Sat May 21 14:28:55 CST 2016
     */
    int updateByExampleSelective(@Param("record") OimMember record,
            @Param("example") OimMemberExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_member
     * @mbggenerated  Sat May 21 14:28:55 CST 2016
     */
    int updateByExample(@Param("record") OimMember record,
            @Param("example") OimMemberExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_member
     * @mbggenerated  Sat May 21 14:28:55 CST 2016
     */
    int updateByPrimaryKeySelective(OimMember record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_member
     * @mbggenerated  Sat May 21 14:28:55 CST 2016
     */
    int updateByPrimaryKey(OimMember record);

    public PageList<OimMember> selectByExample(OimMemberExample example,PageBounds pageBounds);
}