package com.dzmsoft.oim.base.dao;

import com.dzmsoft.oim.base.pojo.OimMallCategory;
import com.dzmsoft.oim.base.pojo.OimMallCategoryExample;
import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface OimMallCategoryMapper {
    public PageList<OimMallCategory> selectByExample(OimMallCategoryExample example,PageBounds pageBounds);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_mall_category
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    int countByExample(OimMallCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_mall_category
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    int deleteByExample(OimMallCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_mall_category
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_mall_category
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    int insert(OimMallCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_mall_category
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    int insertSelective(OimMallCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_mall_category
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    List<OimMallCategory> selectByExample(OimMallCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_mall_category
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    OimMallCategory selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_mall_category
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    int updateByExampleSelective(@Param("record") OimMallCategory record, @Param("example") OimMallCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_mall_category
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    int updateByExample(@Param("record") OimMallCategory record, @Param("example") OimMallCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_mall_category
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    int updateByPrimaryKeySelective(OimMallCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_mall_category
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    int updateByPrimaryKey(OimMallCategory record);
}