package com.dzmsoft.oim.base.dao;

import com.dzmsoft.oim.base.pojo.OimNewhomePriceRule;
import com.dzmsoft.oim.base.pojo.OimNewhomePriceRuleExample;
import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface OimNewhomePriceRuleMapper {
    public PageList<OimNewhomePriceRule> selectByExample(OimNewhomePriceRuleExample example,PageBounds pageBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_newhome_price_rule
     * @mbggenerated  Tue Jun 28 13:16:00 CST 2016
     */
    int countByExample(OimNewhomePriceRuleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_newhome_price_rule
     * @mbggenerated  Tue Jun 28 13:16:00 CST 2016
     */
    int deleteByExample(OimNewhomePriceRuleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_newhome_price_rule
     * @mbggenerated  Tue Jun 28 13:16:00 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_newhome_price_rule
     * @mbggenerated  Tue Jun 28 13:16:00 CST 2016
     */
    int insert(OimNewhomePriceRule record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_newhome_price_rule
     * @mbggenerated  Tue Jun 28 13:16:00 CST 2016
     */
    int insertSelective(OimNewhomePriceRule record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_newhome_price_rule
     * @mbggenerated  Tue Jun 28 13:16:00 CST 2016
     */
    List<OimNewhomePriceRule> selectByExampleWithBLOBs(OimNewhomePriceRuleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_newhome_price_rule
     * @mbggenerated  Tue Jun 28 13:16:00 CST 2016
     */
    List<OimNewhomePriceRule> selectByExample(OimNewhomePriceRuleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_newhome_price_rule
     * @mbggenerated  Tue Jun 28 13:16:00 CST 2016
     */
    OimNewhomePriceRule selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_newhome_price_rule
     * @mbggenerated  Tue Jun 28 13:16:00 CST 2016
     */
    int updateByExampleSelective(@Param("record") OimNewhomePriceRule record,
            @Param("example") OimNewhomePriceRuleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_newhome_price_rule
     * @mbggenerated  Tue Jun 28 13:16:00 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") OimNewhomePriceRule record,
            @Param("example") OimNewhomePriceRuleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_newhome_price_rule
     * @mbggenerated  Tue Jun 28 13:16:00 CST 2016
     */
    int updateByExample(@Param("record") OimNewhomePriceRule record,
            @Param("example") OimNewhomePriceRuleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_newhome_price_rule
     * @mbggenerated  Tue Jun 28 13:16:00 CST 2016
     */
    int updateByPrimaryKeySelective(OimNewhomePriceRule record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_newhome_price_rule
     * @mbggenerated  Tue Jun 28 13:16:00 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(OimNewhomePriceRule record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_newhome_price_rule
     * @mbggenerated  Tue Jun 28 13:16:00 CST 2016
     */
    int updateByPrimaryKey(OimNewhomePriceRule record);
}