package com.dzmsoft.oim.base.dao;

import com.dzmsoft.oim.base.pojo.OimPersonRequireLine;
import com.dzmsoft.oim.base.pojo.OimPersonRequireLineExample;
import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface OimPersonRequireLineMapper {
    public PageList<OimPersonRequireLine> selectByExample(OimPersonRequireLineExample example,PageBounds pageBounds);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_person_require_line
     *
     * @mbggenerated Tue Jun 28 13:16:00 CST 2016
     */
    int countByExample(OimPersonRequireLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_person_require_line
     *
     * @mbggenerated Tue Jun 28 13:16:00 CST 2016
     */
    int deleteByExample(OimPersonRequireLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_person_require_line
     *
     * @mbggenerated Tue Jun 28 13:16:00 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_person_require_line
     *
     * @mbggenerated Tue Jun 28 13:16:00 CST 2016
     */
    int insert(OimPersonRequireLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_person_require_line
     *
     * @mbggenerated Tue Jun 28 13:16:00 CST 2016
     */
    int insertSelective(OimPersonRequireLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_person_require_line
     *
     * @mbggenerated Tue Jun 28 13:16:00 CST 2016
     */
    List<OimPersonRequireLine> selectByExample(OimPersonRequireLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_person_require_line
     *
     * @mbggenerated Tue Jun 28 13:16:00 CST 2016
     */
    OimPersonRequireLine selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_person_require_line
     *
     * @mbggenerated Tue Jun 28 13:16:00 CST 2016
     */
    int updateByExampleSelective(@Param("record") OimPersonRequireLine record, @Param("example") OimPersonRequireLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_person_require_line
     *
     * @mbggenerated Tue Jun 28 13:16:00 CST 2016
     */
    int updateByExample(@Param("record") OimPersonRequireLine record, @Param("example") OimPersonRequireLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_person_require_line
     *
     * @mbggenerated Tue Jun 28 13:16:00 CST 2016
     */
    int updateByPrimaryKeySelective(OimPersonRequireLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_person_require_line
     *
     * @mbggenerated Tue Jun 28 13:16:00 CST 2016
     */
    int updateByPrimaryKey(OimPersonRequireLine record);
}