package com.dzmsoft.oim.base.dao;

import com.dzmsoft.oim.base.pojo.OimSupplier;
import com.dzmsoft.oim.base.pojo.OimSupplierExample;
import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface OimSupplierMapper {
    String selectTopIndex(OimSupplierExample example);
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_supplier
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    int countByExample(OimSupplierExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_supplier
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    int deleteByExample(OimSupplierExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_supplier
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_supplier
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    int insert(OimSupplier record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_supplier
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    int insertSelective(OimSupplier record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_supplier
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    List<OimSupplier> selectByExample(OimSupplierExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_supplier
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    OimSupplier selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_supplier
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    int updateByExampleSelective(@Param("record") OimSupplier record,
            @Param("example") OimSupplierExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_supplier
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    int updateByExample(@Param("record") OimSupplier record,
            @Param("example") OimSupplierExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_supplier
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    int updateByPrimaryKeySelective(OimSupplier record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_supplier
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    int updateByPrimaryKey(OimSupplier record);

    public PageList<OimSupplier> selectByExample(OimSupplierExample example,PageBounds pageBounds);
}