package com.dzmsoft.oim.base.pojo;

import java.util.Date;

public class OimApk {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_apk.id
     *
     * @mbggenerated Wed May 04 13:23:16 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_apk.name
     *
     * @mbggenerated Wed May 04 13:23:16 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_apk.package_name
     *
     * @mbggenerated Wed May 04 13:23:16 CST 2016
     */
    private String packageName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_apk.description
     *
     * @mbggenerated Wed May 04 13:23:16 CST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_apk.apk_file
     *
     * @mbggenerated Wed May 04 13:23:16 CST 2016
     */
    private String apkFile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_apk.apk_name
     *
     * @mbggenerated Wed May 04 13:23:16 CST 2016
     */
    private String apkName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_apk.version
     *
     * @mbggenerated Wed May 04 13:23:16 CST 2016
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_apk.status
     *
     * @mbggenerated Wed May 04 13:23:16 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_apk.creator
     *
     * @mbggenerated Wed May 04 13:23:16 CST 2016
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_apk.create_time
     *
     * @mbggenerated Wed May 04 13:23:16 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_apk.updator
     *
     * @mbggenerated Wed May 04 13:23:16 CST 2016
     */
    private String updator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_apk.update_time
     *
     * @mbggenerated Wed May 04 13:23:16 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_apk.apk_type
     *
     * @mbggenerated Wed May 04 13:23:16 CST 2016
     */
    private String apkType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_apk.id
     *
     * @return the value of oim_apk.id
     *
     * @mbggenerated Wed May 04 13:23:16 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_apk.id
     *
     * @param id the value for oim_apk.id
     *
     * @mbggenerated Wed May 04 13:23:16 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_apk.name
     *
     * @return the value of oim_apk.name
     *
     * @mbggenerated Wed May 04 13:23:16 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_apk.name
     *
     * @param name the value for oim_apk.name
     *
     * @mbggenerated Wed May 04 13:23:16 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_apk.package_name
     *
     * @return the value of oim_apk.package_name
     *
     * @mbggenerated Wed May 04 13:23:16 CST 2016
     */
    public String getPackageName() {
        return packageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_apk.package_name
     *
     * @param packageName the value for oim_apk.package_name
     *
     * @mbggenerated Wed May 04 13:23:16 CST 2016
     */
    public void setPackageName(String packageName) {
        this.packageName = packageName == null ? null : packageName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_apk.description
     *
     * @return the value of oim_apk.description
     *
     * @mbggenerated Wed May 04 13:23:16 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_apk.description
     *
     * @param description the value for oim_apk.description
     *
     * @mbggenerated Wed May 04 13:23:16 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_apk.apk_file
     *
     * @return the value of oim_apk.apk_file
     *
     * @mbggenerated Wed May 04 13:23:16 CST 2016
     */
    public String getApkFile() {
        return apkFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_apk.apk_file
     *
     * @param apkFile the value for oim_apk.apk_file
     *
     * @mbggenerated Wed May 04 13:23:16 CST 2016
     */
    public void setApkFile(String apkFile) {
        this.apkFile = apkFile == null ? null : apkFile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_apk.apk_name
     *
     * @return the value of oim_apk.apk_name
     *
     * @mbggenerated Wed May 04 13:23:16 CST 2016
     */
    public String getApkName() {
        return apkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_apk.apk_name
     *
     * @param apkName the value for oim_apk.apk_name
     *
     * @mbggenerated Wed May 04 13:23:16 CST 2016
     */
    public void setApkName(String apkName) {
        this.apkName = apkName == null ? null : apkName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_apk.version
     *
     * @return the value of oim_apk.version
     *
     * @mbggenerated Wed May 04 13:23:16 CST 2016
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_apk.version
     *
     * @param version the value for oim_apk.version
     *
     * @mbggenerated Wed May 04 13:23:16 CST 2016
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_apk.status
     *
     * @return the value of oim_apk.status
     *
     * @mbggenerated Wed May 04 13:23:16 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_apk.status
     *
     * @param status the value for oim_apk.status
     *
     * @mbggenerated Wed May 04 13:23:16 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_apk.creator
     *
     * @return the value of oim_apk.creator
     *
     * @mbggenerated Wed May 04 13:23:16 CST 2016
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_apk.creator
     *
     * @param creator the value for oim_apk.creator
     *
     * @mbggenerated Wed May 04 13:23:16 CST 2016
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_apk.create_time
     *
     * @return the value of oim_apk.create_time
     *
     * @mbggenerated Wed May 04 13:23:16 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_apk.create_time
     *
     * @param createTime the value for oim_apk.create_time
     *
     * @mbggenerated Wed May 04 13:23:16 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_apk.updator
     *
     * @return the value of oim_apk.updator
     *
     * @mbggenerated Wed May 04 13:23:16 CST 2016
     */
    public String getUpdator() {
        return updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_apk.updator
     *
     * @param updator the value for oim_apk.updator
     *
     * @mbggenerated Wed May 04 13:23:16 CST 2016
     */
    public void setUpdator(String updator) {
        this.updator = updator == null ? null : updator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_apk.update_time
     *
     * @return the value of oim_apk.update_time
     *
     * @mbggenerated Wed May 04 13:23:16 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_apk.update_time
     *
     * @param updateTime the value for oim_apk.update_time
     *
     * @mbggenerated Wed May 04 13:23:16 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_apk.apk_type
     *
     * @return the value of oim_apk.apk_type
     *
     * @mbggenerated Wed May 04 13:23:16 CST 2016
     */
    public String getApkType() {
        return apkType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_apk.apk_type
     *
     * @param apkType the value for oim_apk.apk_type
     *
     * @mbggenerated Wed May 04 13:23:16 CST 2016
     */
    public void setApkType(String apkType) {
        this.apkType = apkType == null ? null : apkType.trim();
    }
}