package com.dzmsoft.oim.base.pojo;

import java.util.Date;

public class OimAdArticle {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column oim_ad_article.id
     * @mbggenerated  Wed Apr 27 13:12:04 CST 2016
     */
    private String id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column oim_ad_article.position
     * @mbggenerated  Wed Apr 27 13:12:04 CST 2016
     */
    private String position;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column oim_ad_article.short_title
     * @mbggenerated  Wed Apr 27 13:12:04 CST 2016
     */
    private String shortTitle;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column oim_ad_article.long_title
     * @mbggenerated  Wed Apr 27 13:12:04 CST 2016
     */
    private String longTitle;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column oim_ad_article.pc_title_pic
     * @mbggenerated  Wed Apr 27 13:12:04 CST 2016
     */
    private String pcTitlePic;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column oim_ad_article.app_title_pic
     * @mbggenerated  Wed Apr 27 13:12:04 CST 2016
     */
    private String appTitlePic;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column oim_ad_article.summary
     * @mbggenerated  Wed Apr 27 13:12:04 CST 2016
     */
    private String summary;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column oim_ad_article.status
     * @mbggenerated  Wed Apr 27 13:12:04 CST 2016
     */
    private String status;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column oim_ad_article.creator
     * @mbggenerated  Wed Apr 27 13:12:04 CST 2016
     */
    private String creator;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column oim_ad_article.create_time
     * @mbggenerated  Wed Apr 27 13:12:04 CST 2016
     */
    private Date createTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column oim_ad_article.deploy_time
     * @mbggenerated  Wed Apr 27 13:12:04 CST 2016
     */
    private Date deployTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column oim_ad_article.updator
     * @mbggenerated  Wed Apr 27 13:12:04 CST 2016
     */
    private String updator;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column oim_ad_article.update_time
     * @mbggenerated  Wed Apr 27 13:12:04 CST 2016
     */
    private Date updateTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column oim_ad_article.context
     * @mbggenerated  Wed Apr 27 13:12:04 CST 2016
     */
    private String context;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column oim_ad_article.id
     * @return  the value of oim_ad_article.id
     * @mbggenerated  Wed Apr 27 13:12:04 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column oim_ad_article.id
     * @param id  the value for oim_ad_article.id
     * @mbggenerated  Wed Apr 27 13:12:04 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column oim_ad_article.position
     * @return  the value of oim_ad_article.position
     * @mbggenerated  Wed Apr 27 13:12:04 CST 2016
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column oim_ad_article.position
     * @param position  the value for oim_ad_article.position
     * @mbggenerated  Wed Apr 27 13:12:04 CST 2016
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column oim_ad_article.short_title
     * @return  the value of oim_ad_article.short_title
     * @mbggenerated  Wed Apr 27 13:12:04 CST 2016
     */
    public String getShortTitle() {
        return shortTitle;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column oim_ad_article.short_title
     * @param shortTitle  the value for oim_ad_article.short_title
     * @mbggenerated  Wed Apr 27 13:12:04 CST 2016
     */
    public void setShortTitle(String shortTitle) {
        this.shortTitle = shortTitle == null ? null : shortTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column oim_ad_article.long_title
     * @return  the value of oim_ad_article.long_title
     * @mbggenerated  Wed Apr 27 13:12:04 CST 2016
     */
    public String getLongTitle() {
        return longTitle;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column oim_ad_article.long_title
     * @param longTitle  the value for oim_ad_article.long_title
     * @mbggenerated  Wed Apr 27 13:12:04 CST 2016
     */
    public void setLongTitle(String longTitle) {
        this.longTitle = longTitle == null ? null : longTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column oim_ad_article.pc_title_pic
     * @return  the value of oim_ad_article.pc_title_pic
     * @mbggenerated  Wed Apr 27 13:12:04 CST 2016
     */
    public String getPcTitlePic() {
        return pcTitlePic;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column oim_ad_article.pc_title_pic
     * @param pcTitlePic  the value for oim_ad_article.pc_title_pic
     * @mbggenerated  Wed Apr 27 13:12:04 CST 2016
     */
    public void setPcTitlePic(String pcTitlePic) {
        this.pcTitlePic = pcTitlePic == null ? null : pcTitlePic.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column oim_ad_article.app_title_pic
     * @return  the value of oim_ad_article.app_title_pic
     * @mbggenerated  Wed Apr 27 13:12:04 CST 2016
     */
    public String getAppTitlePic() {
        return appTitlePic;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column oim_ad_article.app_title_pic
     * @param appTitlePic  the value for oim_ad_article.app_title_pic
     * @mbggenerated  Wed Apr 27 13:12:04 CST 2016
     */
    public void setAppTitlePic(String appTitlePic) {
        this.appTitlePic = appTitlePic == null ? null : appTitlePic.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column oim_ad_article.summary
     * @return  the value of oim_ad_article.summary
     * @mbggenerated  Wed Apr 27 13:12:04 CST 2016
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column oim_ad_article.summary
     * @param summary  the value for oim_ad_article.summary
     * @mbggenerated  Wed Apr 27 13:12:04 CST 2016
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column oim_ad_article.status
     * @return  the value of oim_ad_article.status
     * @mbggenerated  Wed Apr 27 13:12:04 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column oim_ad_article.status
     * @param status  the value for oim_ad_article.status
     * @mbggenerated  Wed Apr 27 13:12:04 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column oim_ad_article.creator
     * @return  the value of oim_ad_article.creator
     * @mbggenerated  Wed Apr 27 13:12:04 CST 2016
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column oim_ad_article.creator
     * @param creator  the value for oim_ad_article.creator
     * @mbggenerated  Wed Apr 27 13:12:04 CST 2016
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column oim_ad_article.create_time
     * @return  the value of oim_ad_article.create_time
     * @mbggenerated  Wed Apr 27 13:12:04 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column oim_ad_article.create_time
     * @param createTime  the value for oim_ad_article.create_time
     * @mbggenerated  Wed Apr 27 13:12:04 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column oim_ad_article.deploy_time
     * @return  the value of oim_ad_article.deploy_time
     * @mbggenerated  Wed Apr 27 13:12:04 CST 2016
     */
    public Date getDeployTime() {
        return deployTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column oim_ad_article.deploy_time
     * @param deployTime  the value for oim_ad_article.deploy_time
     * @mbggenerated  Wed Apr 27 13:12:04 CST 2016
     */
    public void setDeployTime(Date deployTime) {
        this.deployTime = deployTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column oim_ad_article.updator
     * @return  the value of oim_ad_article.updator
     * @mbggenerated  Wed Apr 27 13:12:04 CST 2016
     */
    public String getUpdator() {
        return updator;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column oim_ad_article.updator
     * @param updator  the value for oim_ad_article.updator
     * @mbggenerated  Wed Apr 27 13:12:04 CST 2016
     */
    public void setUpdator(String updator) {
        this.updator = updator == null ? null : updator.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column oim_ad_article.update_time
     * @return  the value of oim_ad_article.update_time
     * @mbggenerated  Wed Apr 27 13:12:04 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column oim_ad_article.update_time
     * @param updateTime  the value for oim_ad_article.update_time
     * @mbggenerated  Wed Apr 27 13:12:04 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column oim_ad_article.context
     * @return  the value of oim_ad_article.context
     * @mbggenerated  Wed Apr 27 13:12:04 CST 2016
     */
    public String getContext() {
        return context;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column oim_ad_article.context
     * @param context  the value for oim_ad_article.context
     * @mbggenerated  Wed Apr 27 13:12:04 CST 2016
     */
    public void setContext(String context) {
        this.context = context == null ? null : context.trim();
    }
}