package com.dzmsoft.oim.base.pojo;

public class OimAdRegion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_ad_region.id
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_ad_region.ad_region_id
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    private String adRegionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_ad_region.ad_article_id
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    private String adArticleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_ad_region.id
     *
     * @return the value of oim_ad_region.id
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_ad_region.id
     *
     * @param id the value for oim_ad_region.id
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_ad_region.ad_region_id
     *
     * @return the value of oim_ad_region.ad_region_id
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public String getAdRegionId() {
        return adRegionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_ad_region.ad_region_id
     *
     * @param adRegionId the value for oim_ad_region.ad_region_id
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public void setAdRegionId(String adRegionId) {
        this.adRegionId = adRegionId == null ? null : adRegionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_ad_region.ad_article_id
     *
     * @return the value of oim_ad_region.ad_article_id
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public String getAdArticleId() {
        return adArticleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_ad_region.ad_article_id
     *
     * @param adArticleId the value for oim_ad_region.ad_article_id
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public void setAdArticleId(String adArticleId) {
        this.adArticleId = adArticleId == null ? null : adArticleId.trim();
    }
}