package com.dzmsoft.oim.base.pojo;

public class OimAdPosition {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_ad_position.id
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_ad_position.name
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_ad_position.pid
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    private String pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_ad_position.status
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_ad_position.description
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_ad_position.id
     *
     * @return the value of oim_ad_position.id
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_ad_position.id
     *
     * @param id the value for oim_ad_position.id
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_ad_position.name
     *
     * @return the value of oim_ad_position.name
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_ad_position.name
     *
     * @param name the value for oim_ad_position.name
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_ad_position.pid
     *
     * @return the value of oim_ad_position.pid
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_ad_position.pid
     *
     * @param pid the value for oim_ad_position.pid
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public void setPid(String pid) {
        this.pid = pid == null ? null : pid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_ad_position.status
     *
     * @return the value of oim_ad_position.status
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_ad_position.status
     *
     * @param status the value for oim_ad_position.status
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_ad_position.description
     *
     * @return the value of oim_ad_position.description
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_ad_position.description
     *
     * @param description the value for oim_ad_position.description
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}