package com.dzmsoft.oim.base.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class OimCard {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_card.id
     *
     * @mbggenerated Tue Jun 28 13:19:02 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_card.name
     *
     * @mbggenerated Tue Jun 28 13:19:02 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_card.face_value
     *
     * @mbggenerated Tue Jun 28 13:19:02 CST 2016
     */
    private BigDecimal faceValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_card.effective_date
     *
     * @mbggenerated Tue Jun 28 13:19:02 CST 2016
     */
    private Date effectiveDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_card.expieration_date
     *
     * @mbggenerated Tue Jun 28 13:19:02 CST 2016
     */
    private Date expierationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_card.status
     *
     * @mbggenerated Tue Jun 28 13:19:02 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_card.create_time
     *
     * @mbggenerated Tue Jun 28 13:19:02 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_card.creator
     *
     * @mbggenerated Tue Jun 28 13:19:02 CST 2016
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_card.description
     *
     * @mbggenerated Tue Jun 28 13:19:02 CST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_card.supplier
     *
     * @mbggenerated Tue Jun 28 13:19:02 CST 2016
     */
    private String supplier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_card.background_pic
     *
     * @mbggenerated Tue Jun 28 13:19:02 CST 2016
     */
    private String backgroundPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_card.content
     *
     * @mbggenerated Tue Jun 28 13:19:02 CST 2016
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_card.id
     *
     * @return the value of oim_card.id
     *
     * @mbggenerated Tue Jun 28 13:19:02 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_card.id
     *
     * @param id the value for oim_card.id
     *
     * @mbggenerated Tue Jun 28 13:19:02 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_card.name
     *
     * @return the value of oim_card.name
     *
     * @mbggenerated Tue Jun 28 13:19:02 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_card.name
     *
     * @param name the value for oim_card.name
     *
     * @mbggenerated Tue Jun 28 13:19:02 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_card.face_value
     *
     * @return the value of oim_card.face_value
     *
     * @mbggenerated Tue Jun 28 13:19:02 CST 2016
     */
    public BigDecimal getFaceValue() {
        return faceValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_card.face_value
     *
     * @param faceValue the value for oim_card.face_value
     *
     * @mbggenerated Tue Jun 28 13:19:02 CST 2016
     */
    public void setFaceValue(BigDecimal faceValue) {
        this.faceValue = faceValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_card.effective_date
     *
     * @return the value of oim_card.effective_date
     *
     * @mbggenerated Tue Jun 28 13:19:02 CST 2016
     */
    public Date getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_card.effective_date
     *
     * @param effectiveDate the value for oim_card.effective_date
     *
     * @mbggenerated Tue Jun 28 13:19:02 CST 2016
     */
    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_card.expieration_date
     *
     * @return the value of oim_card.expieration_date
     *
     * @mbggenerated Tue Jun 28 13:19:02 CST 2016
     */
    public Date getExpierationDate() {
        return expierationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_card.expieration_date
     *
     * @param expierationDate the value for oim_card.expieration_date
     *
     * @mbggenerated Tue Jun 28 13:19:02 CST 2016
     */
    public void setExpierationDate(Date expierationDate) {
        this.expierationDate = expierationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_card.status
     *
     * @return the value of oim_card.status
     *
     * @mbggenerated Tue Jun 28 13:19:02 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_card.status
     *
     * @param status the value for oim_card.status
     *
     * @mbggenerated Tue Jun 28 13:19:02 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_card.create_time
     *
     * @return the value of oim_card.create_time
     *
     * @mbggenerated Tue Jun 28 13:19:02 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_card.create_time
     *
     * @param createTime the value for oim_card.create_time
     *
     * @mbggenerated Tue Jun 28 13:19:02 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_card.creator
     *
     * @return the value of oim_card.creator
     *
     * @mbggenerated Tue Jun 28 13:19:02 CST 2016
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_card.creator
     *
     * @param creator the value for oim_card.creator
     *
     * @mbggenerated Tue Jun 28 13:19:02 CST 2016
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_card.description
     *
     * @return the value of oim_card.description
     *
     * @mbggenerated Tue Jun 28 13:19:02 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_card.description
     *
     * @param description the value for oim_card.description
     *
     * @mbggenerated Tue Jun 28 13:19:02 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_card.supplier
     *
     * @return the value of oim_card.supplier
     *
     * @mbggenerated Tue Jun 28 13:19:02 CST 2016
     */
    public String getSupplier() {
        return supplier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_card.supplier
     *
     * @param supplier the value for oim_card.supplier
     *
     * @mbggenerated Tue Jun 28 13:19:02 CST 2016
     */
    public void setSupplier(String supplier) {
        this.supplier = supplier == null ? null : supplier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_card.background_pic
     *
     * @return the value of oim_card.background_pic
     *
     * @mbggenerated Tue Jun 28 13:19:02 CST 2016
     */
    public String getBackgroundPic() {
        return backgroundPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_card.background_pic
     *
     * @param backgroundPic the value for oim_card.background_pic
     *
     * @mbggenerated Tue Jun 28 13:19:02 CST 2016
     */
    public void setBackgroundPic(String backgroundPic) {
        this.backgroundPic = backgroundPic == null ? null : backgroundPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_card.content
     *
     * @return the value of oim_card.content
     *
     * @mbggenerated Tue Jun 28 13:19:02 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_card.content
     *
     * @param content the value for oim_card.content
     *
     * @mbggenerated Tue Jun 28 13:19:02 CST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}