package com.dzmsoft.oim.base.pojo;

import java.util.Date;

public class OimCleanBag {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_clean_bag.id
     *
     * @mbggenerated Tue Jun 28 13:16:00 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_clean_bag.effective_date
     *
     * @mbggenerated Tue Jun 28 13:16:00 CST 2016
     */
    private Date effectiveDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_clean_bag.expiration_date
     *
     * @mbggenerated Tue Jun 28 13:16:00 CST 2016
     */
    private Date expirationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_clean_bag.status
     *
     * @mbggenerated Tue Jun 28 13:16:00 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_clean_bag.description
     *
     * @mbggenerated Tue Jun 28 13:16:00 CST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_clean_bag.creator
     *
     * @mbggenerated Tue Jun 28 13:16:00 CST 2016
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_clean_bag.create_time
     *
     * @mbggenerated Tue Jun 28 13:16:00 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_clean_bag.name
     *
     * @mbggenerated Tue Jun 28 13:16:00 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_clean_bag.operate_region
     *
     * @mbggenerated Tue Jun 28 13:16:00 CST 2016
     */
    private String operateRegion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_clean_bag.id
     *
     * @return the value of oim_clean_bag.id
     *
     * @mbggenerated Tue Jun 28 13:16:00 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_clean_bag.id
     *
     * @param id the value for oim_clean_bag.id
     *
     * @mbggenerated Tue Jun 28 13:16:00 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_clean_bag.effective_date
     *
     * @return the value of oim_clean_bag.effective_date
     *
     * @mbggenerated Tue Jun 28 13:16:00 CST 2016
     */
    public Date getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_clean_bag.effective_date
     *
     * @param effectiveDate the value for oim_clean_bag.effective_date
     *
     * @mbggenerated Tue Jun 28 13:16:00 CST 2016
     */
    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_clean_bag.expiration_date
     *
     * @return the value of oim_clean_bag.expiration_date
     *
     * @mbggenerated Tue Jun 28 13:16:00 CST 2016
     */
    public Date getExpirationDate() {
        return expirationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_clean_bag.expiration_date
     *
     * @param expirationDate the value for oim_clean_bag.expiration_date
     *
     * @mbggenerated Tue Jun 28 13:16:00 CST 2016
     */
    public void setExpirationDate(Date expirationDate) {
        this.expirationDate = expirationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_clean_bag.status
     *
     * @return the value of oim_clean_bag.status
     *
     * @mbggenerated Tue Jun 28 13:16:00 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_clean_bag.status
     *
     * @param status the value for oim_clean_bag.status
     *
     * @mbggenerated Tue Jun 28 13:16:00 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_clean_bag.description
     *
     * @return the value of oim_clean_bag.description
     *
     * @mbggenerated Tue Jun 28 13:16:00 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_clean_bag.description
     *
     * @param description the value for oim_clean_bag.description
     *
     * @mbggenerated Tue Jun 28 13:16:00 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_clean_bag.creator
     *
     * @return the value of oim_clean_bag.creator
     *
     * @mbggenerated Tue Jun 28 13:16:00 CST 2016
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_clean_bag.creator
     *
     * @param creator the value for oim_clean_bag.creator
     *
     * @mbggenerated Tue Jun 28 13:16:00 CST 2016
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_clean_bag.create_time
     *
     * @return the value of oim_clean_bag.create_time
     *
     * @mbggenerated Tue Jun 28 13:16:00 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_clean_bag.create_time
     *
     * @param createTime the value for oim_clean_bag.create_time
     *
     * @mbggenerated Tue Jun 28 13:16:00 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_clean_bag.name
     *
     * @return the value of oim_clean_bag.name
     *
     * @mbggenerated Tue Jun 28 13:16:00 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_clean_bag.name
     *
     * @param name the value for oim_clean_bag.name
     *
     * @mbggenerated Tue Jun 28 13:16:00 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_clean_bag.operate_region
     *
     * @return the value of oim_clean_bag.operate_region
     *
     * @mbggenerated Tue Jun 28 13:16:00 CST 2016
     */
    public String getOperateRegion() {
        return operateRegion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_clean_bag.operate_region
     *
     * @param operateRegion the value for oim_clean_bag.operate_region
     *
     * @mbggenerated Tue Jun 28 13:16:00 CST 2016
     */
    public void setOperateRegion(String operateRegion) {
        this.operateRegion = operateRegion == null ? null : operateRegion.trim();
    }
}