package com.dzmsoft.oim.base.pojo;

import java.util.Date;

public class OimEmployee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_employee.id
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_employee.name
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_employee.sex
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_employee.birthday
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_employee.description
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_employee.id_card
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_employee.head_portrail_pic
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    private String headPortrailPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_employee.ucs_id
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    private String ucsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_employee.mobile
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_employee.status
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_employee.user_type
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    private String userType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_employee.id
     *
     * @return the value of oim_employee.id
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_employee.id
     *
     * @param id the value for oim_employee.id
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_employee.name
     *
     * @return the value of oim_employee.name
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_employee.name
     *
     * @param name the value for oim_employee.name
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_employee.sex
     *
     * @return the value of oim_employee.sex
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_employee.sex
     *
     * @param sex the value for oim_employee.sex
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_employee.birthday
     *
     * @return the value of oim_employee.birthday
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_employee.birthday
     *
     * @param birthday the value for oim_employee.birthday
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_employee.description
     *
     * @return the value of oim_employee.description
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_employee.description
     *
     * @param description the value for oim_employee.description
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_employee.id_card
     *
     * @return the value of oim_employee.id_card
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_employee.id_card
     *
     * @param idCard the value for oim_employee.id_card
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_employee.head_portrail_pic
     *
     * @return the value of oim_employee.head_portrail_pic
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public String getHeadPortrailPic() {
        return headPortrailPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_employee.head_portrail_pic
     *
     * @param headPortrailPic the value for oim_employee.head_portrail_pic
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public void setHeadPortrailPic(String headPortrailPic) {
        this.headPortrailPic = headPortrailPic == null ? null : headPortrailPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_employee.ucs_id
     *
     * @return the value of oim_employee.ucs_id
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public String getUcsId() {
        return ucsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_employee.ucs_id
     *
     * @param ucsId the value for oim_employee.ucs_id
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public void setUcsId(String ucsId) {
        this.ucsId = ucsId == null ? null : ucsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_employee.mobile
     *
     * @return the value of oim_employee.mobile
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_employee.mobile
     *
     * @param mobile the value for oim_employee.mobile
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_employee.status
     *
     * @return the value of oim_employee.status
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_employee.status
     *
     * @param status the value for oim_employee.status
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_employee.user_type
     *
     * @return the value of oim_employee.user_type
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_employee.user_type
     *
     * @param userType the value for oim_employee.user_type
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public void setUserType(String userType) {
        this.userType = userType == null ? null : userType.trim();
    }
}