package com.dzmsoft.oim.base.pojo;

public class OimMemberAddress {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_member_address.id
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_member_address.is_default
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    private String isDefault;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_member_address.city
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_member_address.division
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    private String division;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_member_address.short_address
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    private String shortAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_member_address.long_address
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    private String longAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_member_address.ucs_id
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    private String ucsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_member_address.province
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    private String province;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_member_address.id
     *
     * @return the value of oim_member_address.id
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_member_address.id
     *
     * @param id the value for oim_member_address.id
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_member_address.is_default
     *
     * @return the value of oim_member_address.is_default
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public String getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_member_address.is_default
     *
     * @param isDefault the value for oim_member_address.is_default
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public void setIsDefault(String isDefault) {
        this.isDefault = isDefault == null ? null : isDefault.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_member_address.city
     *
     * @return the value of oim_member_address.city
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_member_address.city
     *
     * @param city the value for oim_member_address.city
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_member_address.division
     *
     * @return the value of oim_member_address.division
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public String getDivision() {
        return division;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_member_address.division
     *
     * @param division the value for oim_member_address.division
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public void setDivision(String division) {
        this.division = division == null ? null : division.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_member_address.short_address
     *
     * @return the value of oim_member_address.short_address
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public String getShortAddress() {
        return shortAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_member_address.short_address
     *
     * @param shortAddress the value for oim_member_address.short_address
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public void setShortAddress(String shortAddress) {
        this.shortAddress = shortAddress == null ? null : shortAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_member_address.long_address
     *
     * @return the value of oim_member_address.long_address
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public String getLongAddress() {
        return longAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_member_address.long_address
     *
     * @param longAddress the value for oim_member_address.long_address
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public void setLongAddress(String longAddress) {
        this.longAddress = longAddress == null ? null : longAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_member_address.ucs_id
     *
     * @return the value of oim_member_address.ucs_id
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public String getUcsId() {
        return ucsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_member_address.ucs_id
     *
     * @param ucsId the value for oim_member_address.ucs_id
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public void setUcsId(String ucsId) {
        this.ucsId = ucsId == null ? null : ucsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_member_address.province
     *
     * @return the value of oim_member_address.province
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_member_address.province
     *
     * @param province the value for oim_member_address.province
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }
}