package com.dzmsoft.oim.base.pojo;

import java.util.ArrayList;
import java.util.List;

public class OimMallCategoryExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oim_mall_category
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oim_mall_category
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oim_mall_category
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_mall_category
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public OimMallCategoryExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_mall_category
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_mall_category
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_mall_category
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_mall_category
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_mall_category
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_mall_category
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_mall_category
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_mall_category
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_mall_category
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oim_mall_category
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table oim_mall_category
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPidIsNull() {
            addCriterion("pid is null");
            return (Criteria) this;
        }

        public Criteria andPidIsNotNull() {
            addCriterion("pid is not null");
            return (Criteria) this;
        }

        public Criteria andPidEqualTo(String value) {
            addCriterion("pid =", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotEqualTo(String value) {
            addCriterion("pid <>", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidGreaterThan(String value) {
            addCriterion("pid >", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidGreaterThanOrEqualTo(String value) {
            addCriterion("pid >=", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLessThan(String value) {
            addCriterion("pid <", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLessThanOrEqualTo(String value) {
            addCriterion("pid <=", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLike(String value) {
            addCriterion("pid like", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotLike(String value) {
            addCriterion("pid not like", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidIn(List<String> values) {
            addCriterion("pid in", values, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotIn(List<String> values) {
            addCriterion("pid not in", values, "pid");
            return (Criteria) this;
        }

        public Criteria andPidBetween(String value1, String value2) {
            addCriterion("pid between", value1, value2, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotBetween(String value1, String value2) {
            addCriterion("pid not between", value1, value2, "pid");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andSiteResourcePathIsNull() {
            addCriterion("site_resource_path is null");
            return (Criteria) this;
        }

        public Criteria andSiteResourcePathIsNotNull() {
            addCriterion("site_resource_path is not null");
            return (Criteria) this;
        }

        public Criteria andSiteResourcePathEqualTo(String value) {
            addCriterion("site_resource_path =", value, "siteResourcePath");
            return (Criteria) this;
        }

        public Criteria andSiteResourcePathNotEqualTo(String value) {
            addCriterion("site_resource_path <>", value, "siteResourcePath");
            return (Criteria) this;
        }

        public Criteria andSiteResourcePathGreaterThan(String value) {
            addCriterion("site_resource_path >", value, "siteResourcePath");
            return (Criteria) this;
        }

        public Criteria andSiteResourcePathGreaterThanOrEqualTo(String value) {
            addCriterion("site_resource_path >=", value, "siteResourcePath");
            return (Criteria) this;
        }

        public Criteria andSiteResourcePathLessThan(String value) {
            addCriterion("site_resource_path <", value, "siteResourcePath");
            return (Criteria) this;
        }

        public Criteria andSiteResourcePathLessThanOrEqualTo(String value) {
            addCriterion("site_resource_path <=", value, "siteResourcePath");
            return (Criteria) this;
        }

        public Criteria andSiteResourcePathLike(String value) {
            addCriterion("site_resource_path like", value, "siteResourcePath");
            return (Criteria) this;
        }

        public Criteria andSiteResourcePathNotLike(String value) {
            addCriterion("site_resource_path not like", value, "siteResourcePath");
            return (Criteria) this;
        }

        public Criteria andSiteResourcePathIn(List<String> values) {
            addCriterion("site_resource_path in", values, "siteResourcePath");
            return (Criteria) this;
        }

        public Criteria andSiteResourcePathNotIn(List<String> values) {
            addCriterion("site_resource_path not in", values, "siteResourcePath");
            return (Criteria) this;
        }

        public Criteria andSiteResourcePathBetween(String value1, String value2) {
            addCriterion("site_resource_path between", value1, value2, "siteResourcePath");
            return (Criteria) this;
        }

        public Criteria andSiteResourcePathNotBetween(String value1, String value2) {
            addCriterion("site_resource_path not between", value1, value2, "siteResourcePath");
            return (Criteria) this;
        }

        public Criteria andPhoneResourcePathIsNull() {
            addCriterion("phone_resource_path is null");
            return (Criteria) this;
        }

        public Criteria andPhoneResourcePathIsNotNull() {
            addCriterion("phone_resource_path is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneResourcePathEqualTo(String value) {
            addCriterion("phone_resource_path =", value, "phoneResourcePath");
            return (Criteria) this;
        }

        public Criteria andPhoneResourcePathNotEqualTo(String value) {
            addCriterion("phone_resource_path <>", value, "phoneResourcePath");
            return (Criteria) this;
        }

        public Criteria andPhoneResourcePathGreaterThan(String value) {
            addCriterion("phone_resource_path >", value, "phoneResourcePath");
            return (Criteria) this;
        }

        public Criteria andPhoneResourcePathGreaterThanOrEqualTo(String value) {
            addCriterion("phone_resource_path >=", value, "phoneResourcePath");
            return (Criteria) this;
        }

        public Criteria andPhoneResourcePathLessThan(String value) {
            addCriterion("phone_resource_path <", value, "phoneResourcePath");
            return (Criteria) this;
        }

        public Criteria andPhoneResourcePathLessThanOrEqualTo(String value) {
            addCriterion("phone_resource_path <=", value, "phoneResourcePath");
            return (Criteria) this;
        }

        public Criteria andPhoneResourcePathLike(String value) {
            addCriterion("phone_resource_path like", value, "phoneResourcePath");
            return (Criteria) this;
        }

        public Criteria andPhoneResourcePathNotLike(String value) {
            addCriterion("phone_resource_path not like", value, "phoneResourcePath");
            return (Criteria) this;
        }

        public Criteria andPhoneResourcePathIn(List<String> values) {
            addCriterion("phone_resource_path in", values, "phoneResourcePath");
            return (Criteria) this;
        }

        public Criteria andPhoneResourcePathNotIn(List<String> values) {
            addCriterion("phone_resource_path not in", values, "phoneResourcePath");
            return (Criteria) this;
        }

        public Criteria andPhoneResourcePathBetween(String value1, String value2) {
            addCriterion("phone_resource_path between", value1, value2, "phoneResourcePath");
            return (Criteria) this;
        }

        public Criteria andPhoneResourcePathNotBetween(String value1, String value2) {
            addCriterion("phone_resource_path not between", value1, value2, "phoneResourcePath");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andSortIsNull() {
            addCriterion("sort is null");
            return (Criteria) this;
        }

        public Criteria andSortIsNotNull() {
            addCriterion("sort is not null");
            return (Criteria) this;
        }

        public Criteria andSortEqualTo(Integer value) {
            addCriterion("sort =", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortNotEqualTo(Integer value) {
            addCriterion("sort <>", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortGreaterThan(Integer value) {
            addCriterion("sort >", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortGreaterThanOrEqualTo(Integer value) {
            addCriterion("sort >=", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortLessThan(Integer value) {
            addCriterion("sort <", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortLessThanOrEqualTo(Integer value) {
            addCriterion("sort <=", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortIn(List<Integer> values) {
            addCriterion("sort in", values, "sort");
            return (Criteria) this;
        }

        public Criteria andSortNotIn(List<Integer> values) {
            addCriterion("sort not in", values, "sort");
            return (Criteria) this;
        }

        public Criteria andSortBetween(Integer value1, Integer value2) {
            addCriterion("sort between", value1, value2, "sort");
            return (Criteria) this;
        }

        public Criteria andSortNotBetween(Integer value1, Integer value2) {
            addCriterion("sort not between", value1, value2, "sort");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table oim_mall_category
     *
     * @mbggenerated do_not_delete_during_merge Tue Apr 26 13:59:10 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table oim_mall_category
     *
     * @mbggenerated Tue Apr 26 13:59:10 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}