package com.dzmsoft.oim.base.pojo;

import java.util.Date;

public class OimMember {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column oim_member.id
     * @mbggenerated  Sat May 21 14:28:55 CST 2016
     */
    private String id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column oim_member.name
     * @mbggenerated  Sat May 21 14:28:55 CST 2016
     */
    private String name;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column oim_member.sex
     * @mbggenerated  Sat May 21 14:28:55 CST 2016
     */
    private String sex;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column oim_member.mobile
     * @mbggenerated  Sat May 21 14:28:55 CST 2016
     */
    private String mobile;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column oim_member.ucs_id
     * @mbggenerated  Sat May 21 14:28:55 CST 2016
     */
    private String ucsId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column oim_member.create_time
     * @mbggenerated  Sat May 21 14:28:55 CST 2016
     */
    private Date createTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column oim_member.city
     * @mbggenerated  Sat May 21 14:28:55 CST 2016
     */
    private String city;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column oim_member.province
     * @mbggenerated  Sat May 21 14:28:55 CST 2016
     */
    private String province;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column oim_member.division
     * @mbggenerated  Sat May 21 14:28:55 CST 2016
     */
    private String division;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column oim_member.header_pic
     * @mbggenerated  Sat May 21 14:28:55 CST 2016
     */
    private String headerPic;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column oim_member.id
     * @return  the value of oim_member.id
     * @mbggenerated  Sat May 21 14:28:55 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column oim_member.id
     * @param id  the value for oim_member.id
     * @mbggenerated  Sat May 21 14:28:55 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column oim_member.name
     * @return  the value of oim_member.name
     * @mbggenerated  Sat May 21 14:28:55 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column oim_member.name
     * @param name  the value for oim_member.name
     * @mbggenerated  Sat May 21 14:28:55 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column oim_member.sex
     * @return  the value of oim_member.sex
     * @mbggenerated  Sat May 21 14:28:55 CST 2016
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column oim_member.sex
     * @param sex  the value for oim_member.sex
     * @mbggenerated  Sat May 21 14:28:55 CST 2016
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column oim_member.mobile
     * @return  the value of oim_member.mobile
     * @mbggenerated  Sat May 21 14:28:55 CST 2016
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column oim_member.mobile
     * @param mobile  the value for oim_member.mobile
     * @mbggenerated  Sat May 21 14:28:55 CST 2016
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column oim_member.ucs_id
     * @return  the value of oim_member.ucs_id
     * @mbggenerated  Sat May 21 14:28:55 CST 2016
     */
    public String getUcsId() {
        return ucsId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column oim_member.ucs_id
     * @param ucsId  the value for oim_member.ucs_id
     * @mbggenerated  Sat May 21 14:28:55 CST 2016
     */
    public void setUcsId(String ucsId) {
        this.ucsId = ucsId == null ? null : ucsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column oim_member.create_time
     * @return  the value of oim_member.create_time
     * @mbggenerated  Sat May 21 14:28:55 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column oim_member.create_time
     * @param createTime  the value for oim_member.create_time
     * @mbggenerated  Sat May 21 14:28:55 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column oim_member.city
     * @return  the value of oim_member.city
     * @mbggenerated  Sat May 21 14:28:55 CST 2016
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column oim_member.city
     * @param city  the value for oim_member.city
     * @mbggenerated  Sat May 21 14:28:55 CST 2016
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column oim_member.province
     * @return  the value of oim_member.province
     * @mbggenerated  Sat May 21 14:28:55 CST 2016
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column oim_member.province
     * @param province  the value for oim_member.province
     * @mbggenerated  Sat May 21 14:28:55 CST 2016
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column oim_member.division
     * @return  the value of oim_member.division
     * @mbggenerated  Sat May 21 14:28:55 CST 2016
     */
    public String getDivision() {
        return division;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column oim_member.division
     * @param division  the value for oim_member.division
     * @mbggenerated  Sat May 21 14:28:55 CST 2016
     */
    public void setDivision(String division) {
        this.division = division == null ? null : division.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column oim_member.header_pic
     * @return  the value of oim_member.header_pic
     * @mbggenerated  Sat May 21 14:28:55 CST 2016
     */
    public String getHeaderPic() {
        return headerPic;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column oim_member.header_pic
     * @param headerPic  the value for oim_member.header_pic
     * @mbggenerated  Sat May 21 14:28:55 CST 2016
     */
    public void setHeaderPic(String headerPic) {
        this.headerPic = headerPic == null ? null : headerPic.trim();
    }
}