package com.dzmsoft.oim.base.pojo;

public class OimPersonRequireLine {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_person_require_line.id
     *
     * @mbggenerated Tue Jun 28 13:16:00 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_person_require_line.requirement
     *
     * @mbggenerated Tue Jun 28 13:16:00 CST 2016
     */
    private String requirement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oim_person_require_line.require_id
     *
     * @mbggenerated Tue Jun 28 13:16:00 CST 2016
     */
    private String requireId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_person_require_line.id
     *
     * @return the value of oim_person_require_line.id
     *
     * @mbggenerated Tue Jun 28 13:16:00 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_person_require_line.id
     *
     * @param id the value for oim_person_require_line.id
     *
     * @mbggenerated Tue Jun 28 13:16:00 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_person_require_line.requirement
     *
     * @return the value of oim_person_require_line.requirement
     *
     * @mbggenerated Tue Jun 28 13:16:00 CST 2016
     */
    public String getRequirement() {
        return requirement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_person_require_line.requirement
     *
     * @param requirement the value for oim_person_require_line.requirement
     *
     * @mbggenerated Tue Jun 28 13:16:00 CST 2016
     */
    public void setRequirement(String requirement) {
        this.requirement = requirement == null ? null : requirement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oim_person_require_line.require_id
     *
     * @return the value of oim_person_require_line.require_id
     *
     * @mbggenerated Tue Jun 28 13:16:00 CST 2016
     */
    public String getRequireId() {
        return requireId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oim_person_require_line.require_id
     *
     * @param requireId the value for oim_person_require_line.require_id
     *
     * @mbggenerated Tue Jun 28 13:16:00 CST 2016
     */
    public void setRequireId(String requireId) {
        this.requireId = requireId == null ? null : requireId.trim();
    }
}