package com.dzmsoft.oim.base.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class OimSupplierExample {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table oim_supplier
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    protected String orderByClause;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table oim_supplier
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    protected boolean distinct;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table oim_supplier
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_supplier
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    public OimSupplierExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_supplier
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_supplier
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_supplier
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_supplier
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_supplier
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_supplier
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_supplier
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_supplier
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_supplier
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oim_supplier
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table oim_supplier
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property
                        + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2,
                String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(
                    condition,
                    new java.sql.Date(value1.getTime()),
                    new java.sql.Date(value2.getTime()),
                    property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andChiefIsNull() {
            addCriterion("chief is null");
            return (Criteria) this;
        }

        public Criteria andChiefIsNotNull() {
            addCriterion("chief is not null");
            return (Criteria) this;
        }

        public Criteria andChiefEqualTo(String value) {
            addCriterion("chief =", value, "chief");
            return (Criteria) this;
        }

        public Criteria andChiefNotEqualTo(String value) {
            addCriterion("chief <>", value, "chief");
            return (Criteria) this;
        }

        public Criteria andChiefGreaterThan(String value) {
            addCriterion("chief >", value, "chief");
            return (Criteria) this;
        }

        public Criteria andChiefGreaterThanOrEqualTo(String value) {
            addCriterion("chief >=", value, "chief");
            return (Criteria) this;
        }

        public Criteria andChiefLessThan(String value) {
            addCriterion("chief <", value, "chief");
            return (Criteria) this;
        }

        public Criteria andChiefLessThanOrEqualTo(String value) {
            addCriterion("chief <=", value, "chief");
            return (Criteria) this;
        }

        public Criteria andChiefLike(String value) {
            addCriterion("chief like", value, "chief");
            return (Criteria) this;
        }

        public Criteria andChiefNotLike(String value) {
            addCriterion("chief not like", value, "chief");
            return (Criteria) this;
        }

        public Criteria andChiefIn(List<String> values) {
            addCriterion("chief in", values, "chief");
            return (Criteria) this;
        }

        public Criteria andChiefNotIn(List<String> values) {
            addCriterion("chief not in", values, "chief");
            return (Criteria) this;
        }

        public Criteria andChiefBetween(String value1, String value2) {
            addCriterion("chief between", value1, value2, "chief");
            return (Criteria) this;
        }

        public Criteria andChiefNotBetween(String value1, String value2) {
            addCriterion("chief not between", value1, value2, "chief");
            return (Criteria) this;
        }

        public Criteria andChiefPhoneIsNull() {
            addCriterion("chief_phone is null");
            return (Criteria) this;
        }

        public Criteria andChiefPhoneIsNotNull() {
            addCriterion("chief_phone is not null");
            return (Criteria) this;
        }

        public Criteria andChiefPhoneEqualTo(String value) {
            addCriterion("chief_phone =", value, "chiefPhone");
            return (Criteria) this;
        }

        public Criteria andChiefPhoneNotEqualTo(String value) {
            addCriterion("chief_phone <>", value, "chiefPhone");
            return (Criteria) this;
        }

        public Criteria andChiefPhoneGreaterThan(String value) {
            addCriterion("chief_phone >", value, "chiefPhone");
            return (Criteria) this;
        }

        public Criteria andChiefPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("chief_phone >=", value, "chiefPhone");
            return (Criteria) this;
        }

        public Criteria andChiefPhoneLessThan(String value) {
            addCriterion("chief_phone <", value, "chiefPhone");
            return (Criteria) this;
        }

        public Criteria andChiefPhoneLessThanOrEqualTo(String value) {
            addCriterion("chief_phone <=", value, "chiefPhone");
            return (Criteria) this;
        }

        public Criteria andChiefPhoneLike(String value) {
            addCriterion("chief_phone like", value, "chiefPhone");
            return (Criteria) this;
        }

        public Criteria andChiefPhoneNotLike(String value) {
            addCriterion("chief_phone not like", value, "chiefPhone");
            return (Criteria) this;
        }

        public Criteria andChiefPhoneIn(List<String> values) {
            addCriterion("chief_phone in", values, "chiefPhone");
            return (Criteria) this;
        }

        public Criteria andChiefPhoneNotIn(List<String> values) {
            addCriterion("chief_phone not in", values, "chiefPhone");
            return (Criteria) this;
        }

        public Criteria andChiefPhoneBetween(String value1, String value2) {
            addCriterion("chief_phone between", value1, value2, "chiefPhone");
            return (Criteria) this;
        }

        public Criteria andChiefPhoneNotBetween(String value1, String value2) {
            addCriterion("chief_phone not between", value1, value2, "chiefPhone");
            return (Criteria) this;
        }

        public Criteria andJoinDateIsNull() {
            addCriterion("join_date is null");
            return (Criteria) this;
        }

        public Criteria andJoinDateIsNotNull() {
            addCriterion("join_date is not null");
            return (Criteria) this;
        }

        public Criteria andJoinDateEqualTo(Date value) {
            addCriterionForJDBCDate("join_date =", value, "joinDate");
            return (Criteria) this;
        }

        public Criteria andJoinDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("join_date <>", value, "joinDate");
            return (Criteria) this;
        }

        public Criteria andJoinDateGreaterThan(Date value) {
            addCriterionForJDBCDate("join_date >", value, "joinDate");
            return (Criteria) this;
        }

        public Criteria andJoinDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("join_date >=", value, "joinDate");
            return (Criteria) this;
        }

        public Criteria andJoinDateLessThan(Date value) {
            addCriterionForJDBCDate("join_date <", value, "joinDate");
            return (Criteria) this;
        }

        public Criteria andJoinDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("join_date <=", value, "joinDate");
            return (Criteria) this;
        }

        public Criteria andJoinDateIn(List<Date> values) {
            addCriterionForJDBCDate("join_date in", values, "joinDate");
            return (Criteria) this;
        }

        public Criteria andJoinDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("join_date not in", values, "joinDate");
            return (Criteria) this;
        }

        public Criteria andJoinDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("join_date between", value1, value2, "joinDate");
            return (Criteria) this;
        }

        public Criteria andJoinDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("join_date not between", value1, value2, "joinDate");
            return (Criteria) this;
        }

        public Criteria andRegProvinceIsNull() {
            addCriterion("reg_province is null");
            return (Criteria) this;
        }

        public Criteria andRegProvinceIsNotNull() {
            addCriterion("reg_province is not null");
            return (Criteria) this;
        }

        public Criteria andRegProvinceEqualTo(String value) {
            addCriterion("reg_province =", value, "regProvince");
            return (Criteria) this;
        }

        public Criteria andRegProvinceNotEqualTo(String value) {
            addCriterion("reg_province <>", value, "regProvince");
            return (Criteria) this;
        }

        public Criteria andRegProvinceGreaterThan(String value) {
            addCriterion("reg_province >", value, "regProvince");
            return (Criteria) this;
        }

        public Criteria andRegProvinceGreaterThanOrEqualTo(String value) {
            addCriterion("reg_province >=", value, "regProvince");
            return (Criteria) this;
        }

        public Criteria andRegProvinceLessThan(String value) {
            addCriterion("reg_province <", value, "regProvince");
            return (Criteria) this;
        }

        public Criteria andRegProvinceLessThanOrEqualTo(String value) {
            addCriterion("reg_province <=", value, "regProvince");
            return (Criteria) this;
        }

        public Criteria andRegProvinceLike(String value) {
            addCriterion("reg_province like", value, "regProvince");
            return (Criteria) this;
        }

        public Criteria andRegProvinceNotLike(String value) {
            addCriterion("reg_province not like", value, "regProvince");
            return (Criteria) this;
        }

        public Criteria andRegProvinceIn(List<String> values) {
            addCriterion("reg_province in", values, "regProvince");
            return (Criteria) this;
        }

        public Criteria andRegProvinceNotIn(List<String> values) {
            addCriterion("reg_province not in", values, "regProvince");
            return (Criteria) this;
        }

        public Criteria andRegProvinceBetween(String value1, String value2) {
            addCriterion("reg_province between", value1, value2, "regProvince");
            return (Criteria) this;
        }

        public Criteria andRegProvinceNotBetween(String value1, String value2) {
            addCriterion("reg_province not between", value1, value2, "regProvince");
            return (Criteria) this;
        }

        public Criteria andShortNameIsNull() {
            addCriterion("short_name is null");
            return (Criteria) this;
        }

        public Criteria andShortNameIsNotNull() {
            addCriterion("short_name is not null");
            return (Criteria) this;
        }

        public Criteria andShortNameEqualTo(String value) {
            addCriterion("short_name =", value, "shortName");
            return (Criteria) this;
        }

        public Criteria andShortNameNotEqualTo(String value) {
            addCriterion("short_name <>", value, "shortName");
            return (Criteria) this;
        }

        public Criteria andShortNameGreaterThan(String value) {
            addCriterion("short_name >", value, "shortName");
            return (Criteria) this;
        }

        public Criteria andShortNameGreaterThanOrEqualTo(String value) {
            addCriterion("short_name >=", value, "shortName");
            return (Criteria) this;
        }

        public Criteria andShortNameLessThan(String value) {
            addCriterion("short_name <", value, "shortName");
            return (Criteria) this;
        }

        public Criteria andShortNameLessThanOrEqualTo(String value) {
            addCriterion("short_name <=", value, "shortName");
            return (Criteria) this;
        }

        public Criteria andShortNameLike(String value) {
            addCriterion("short_name like", value, "shortName");
            return (Criteria) this;
        }

        public Criteria andShortNameNotLike(String value) {
            addCriterion("short_name not like", value, "shortName");
            return (Criteria) this;
        }

        public Criteria andShortNameIn(List<String> values) {
            addCriterion("short_name in", values, "shortName");
            return (Criteria) this;
        }

        public Criteria andShortNameNotIn(List<String> values) {
            addCriterion("short_name not in", values, "shortName");
            return (Criteria) this;
        }

        public Criteria andShortNameBetween(String value1, String value2) {
            addCriterion("short_name between", value1, value2, "shortName");
            return (Criteria) this;
        }

        public Criteria andShortNameNotBetween(String value1, String value2) {
            addCriterion("short_name not between", value1, value2, "shortName");
            return (Criteria) this;
        }

        public Criteria andLogoPicIsNull() {
            addCriterion("logo_pic is null");
            return (Criteria) this;
        }

        public Criteria andLogoPicIsNotNull() {
            addCriterion("logo_pic is not null");
            return (Criteria) this;
        }

        public Criteria andLogoPicEqualTo(String value) {
            addCriterion("logo_pic =", value, "logoPic");
            return (Criteria) this;
        }

        public Criteria andLogoPicNotEqualTo(String value) {
            addCriterion("logo_pic <>", value, "logoPic");
            return (Criteria) this;
        }

        public Criteria andLogoPicGreaterThan(String value) {
            addCriterion("logo_pic >", value, "logoPic");
            return (Criteria) this;
        }

        public Criteria andLogoPicGreaterThanOrEqualTo(String value) {
            addCriterion("logo_pic >=", value, "logoPic");
            return (Criteria) this;
        }

        public Criteria andLogoPicLessThan(String value) {
            addCriterion("logo_pic <", value, "logoPic");
            return (Criteria) this;
        }

        public Criteria andLogoPicLessThanOrEqualTo(String value) {
            addCriterion("logo_pic <=", value, "logoPic");
            return (Criteria) this;
        }

        public Criteria andLogoPicLike(String value) {
            addCriterion("logo_pic like", value, "logoPic");
            return (Criteria) this;
        }

        public Criteria andLogoPicNotLike(String value) {
            addCriterion("logo_pic not like", value, "logoPic");
            return (Criteria) this;
        }

        public Criteria andLogoPicIn(List<String> values) {
            addCriterion("logo_pic in", values, "logoPic");
            return (Criteria) this;
        }

        public Criteria andLogoPicNotIn(List<String> values) {
            addCriterion("logo_pic not in", values, "logoPic");
            return (Criteria) this;
        }

        public Criteria andLogoPicBetween(String value1, String value2) {
            addCriterion("logo_pic between", value1, value2, "logoPic");
            return (Criteria) this;
        }

        public Criteria andLogoPicNotBetween(String value1, String value2) {
            addCriterion("logo_pic not between", value1, value2, "logoPic");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andUcsIdIsNull() {
            addCriterion("ucs_id is null");
            return (Criteria) this;
        }

        public Criteria andUcsIdIsNotNull() {
            addCriterion("ucs_id is not null");
            return (Criteria) this;
        }

        public Criteria andUcsIdEqualTo(String value) {
            addCriterion("ucs_id =", value, "ucsId");
            return (Criteria) this;
        }

        public Criteria andUcsIdNotEqualTo(String value) {
            addCriterion("ucs_id <>", value, "ucsId");
            return (Criteria) this;
        }

        public Criteria andUcsIdGreaterThan(String value) {
            addCriterion("ucs_id >", value, "ucsId");
            return (Criteria) this;
        }

        public Criteria andUcsIdGreaterThanOrEqualTo(String value) {
            addCriterion("ucs_id >=", value, "ucsId");
            return (Criteria) this;
        }

        public Criteria andUcsIdLessThan(String value) {
            addCriterion("ucs_id <", value, "ucsId");
            return (Criteria) this;
        }

        public Criteria andUcsIdLessThanOrEqualTo(String value) {
            addCriterion("ucs_id <=", value, "ucsId");
            return (Criteria) this;
        }

        public Criteria andUcsIdLike(String value) {
            addCriterion("ucs_id like", value, "ucsId");
            return (Criteria) this;
        }

        public Criteria andUcsIdNotLike(String value) {
            addCriterion("ucs_id not like", value, "ucsId");
            return (Criteria) this;
        }

        public Criteria andUcsIdIn(List<String> values) {
            addCriterion("ucs_id in", values, "ucsId");
            return (Criteria) this;
        }

        public Criteria andUcsIdNotIn(List<String> values) {
            addCriterion("ucs_id not in", values, "ucsId");
            return (Criteria) this;
        }

        public Criteria andUcsIdBetween(String value1, String value2) {
            addCriterion("ucs_id between", value1, value2, "ucsId");
            return (Criteria) this;
        }

        public Criteria andUcsIdNotBetween(String value1, String value2) {
            addCriterion("ucs_id not between", value1, value2, "ucsId");
            return (Criteria) this;
        }

        public Criteria andRegCityIsNull() {
            addCriterion("reg_city is null");
            return (Criteria) this;
        }

        public Criteria andRegCityIsNotNull() {
            addCriterion("reg_city is not null");
            return (Criteria) this;
        }

        public Criteria andRegCityEqualTo(String value) {
            addCriterion("reg_city =", value, "regCity");
            return (Criteria) this;
        }

        public Criteria andRegCityNotEqualTo(String value) {
            addCriterion("reg_city <>", value, "regCity");
            return (Criteria) this;
        }

        public Criteria andRegCityGreaterThan(String value) {
            addCriterion("reg_city >", value, "regCity");
            return (Criteria) this;
        }

        public Criteria andRegCityGreaterThanOrEqualTo(String value) {
            addCriterion("reg_city >=", value, "regCity");
            return (Criteria) this;
        }

        public Criteria andRegCityLessThan(String value) {
            addCriterion("reg_city <", value, "regCity");
            return (Criteria) this;
        }

        public Criteria andRegCityLessThanOrEqualTo(String value) {
            addCriterion("reg_city <=", value, "regCity");
            return (Criteria) this;
        }

        public Criteria andRegCityLike(String value) {
            addCriterion("reg_city like", value, "regCity");
            return (Criteria) this;
        }

        public Criteria andRegCityNotLike(String value) {
            addCriterion("reg_city not like", value, "regCity");
            return (Criteria) this;
        }

        public Criteria andRegCityIn(List<String> values) {
            addCriterion("reg_city in", values, "regCity");
            return (Criteria) this;
        }

        public Criteria andRegCityNotIn(List<String> values) {
            addCriterion("reg_city not in", values, "regCity");
            return (Criteria) this;
        }

        public Criteria andRegCityBetween(String value1, String value2) {
            addCriterion("reg_city between", value1, value2, "regCity");
            return (Criteria) this;
        }

        public Criteria andRegCityNotBetween(String value1, String value2) {
            addCriterion("reg_city not between", value1, value2, "regCity");
            return (Criteria) this;
        }

        public Criteria andRegDistrictIsNull() {
            addCriterion("reg_district is null");
            return (Criteria) this;
        }

        public Criteria andRegDistrictIsNotNull() {
            addCriterion("reg_district is not null");
            return (Criteria) this;
        }

        public Criteria andRegDistrictEqualTo(String value) {
            addCriterion("reg_district =", value, "regDistrict");
            return (Criteria) this;
        }

        public Criteria andRegDistrictNotEqualTo(String value) {
            addCriterion("reg_district <>", value, "regDistrict");
            return (Criteria) this;
        }

        public Criteria andRegDistrictGreaterThan(String value) {
            addCriterion("reg_district >", value, "regDistrict");
            return (Criteria) this;
        }

        public Criteria andRegDistrictGreaterThanOrEqualTo(String value) {
            addCriterion("reg_district >=", value, "regDistrict");
            return (Criteria) this;
        }

        public Criteria andRegDistrictLessThan(String value) {
            addCriterion("reg_district <", value, "regDistrict");
            return (Criteria) this;
        }

        public Criteria andRegDistrictLessThanOrEqualTo(String value) {
            addCriterion("reg_district <=", value, "regDistrict");
            return (Criteria) this;
        }

        public Criteria andRegDistrictLike(String value) {
            addCriterion("reg_district like", value, "regDistrict");
            return (Criteria) this;
        }

        public Criteria andRegDistrictNotLike(String value) {
            addCriterion("reg_district not like", value, "regDistrict");
            return (Criteria) this;
        }

        public Criteria andRegDistrictIn(List<String> values) {
            addCriterion("reg_district in", values, "regDistrict");
            return (Criteria) this;
        }

        public Criteria andRegDistrictNotIn(List<String> values) {
            addCriterion("reg_district not in", values, "regDistrict");
            return (Criteria) this;
        }

        public Criteria andRegDistrictBetween(String value1, String value2) {
            addCriterion("reg_district between", value1, value2, "regDistrict");
            return (Criteria) this;
        }

        public Criteria andRegDistrictNotBetween(String value1, String value2) {
            addCriterion("reg_district not between", value1, value2, "regDistrict");
            return (Criteria) this;
        }

        public Criteria andSupplierTypeIsNull() {
            addCriterion("supplier_type is null");
            return (Criteria) this;
        }

        public Criteria andSupplierTypeIsNotNull() {
            addCriterion("supplier_type is not null");
            return (Criteria) this;
        }

        public Criteria andSupplierTypeEqualTo(String value) {
            addCriterion("supplier_type =", value, "supplierType");
            return (Criteria) this;
        }

        public Criteria andSupplierTypeNotEqualTo(String value) {
            addCriterion("supplier_type <>", value, "supplierType");
            return (Criteria) this;
        }

        public Criteria andSupplierTypeGreaterThan(String value) {
            addCriterion("supplier_type >", value, "supplierType");
            return (Criteria) this;
        }

        public Criteria andSupplierTypeGreaterThanOrEqualTo(String value) {
            addCriterion("supplier_type >=", value, "supplierType");
            return (Criteria) this;
        }

        public Criteria andSupplierTypeLessThan(String value) {
            addCriterion("supplier_type <", value, "supplierType");
            return (Criteria) this;
        }

        public Criteria andSupplierTypeLessThanOrEqualTo(String value) {
            addCriterion("supplier_type <=", value, "supplierType");
            return (Criteria) this;
        }

        public Criteria andSupplierTypeLike(String value) {
            addCriterion("supplier_type like", value, "supplierType");
            return (Criteria) this;
        }

        public Criteria andSupplierTypeNotLike(String value) {
            addCriterion("supplier_type not like", value, "supplierType");
            return (Criteria) this;
        }

        public Criteria andSupplierTypeIn(List<String> values) {
            addCriterion("supplier_type in", values, "supplierType");
            return (Criteria) this;
        }

        public Criteria andSupplierTypeNotIn(List<String> values) {
            addCriterion("supplier_type not in", values, "supplierType");
            return (Criteria) this;
        }

        public Criteria andSupplierTypeBetween(String value1, String value2) {
            addCriterion("supplier_type between", value1, value2, "supplierType");
            return (Criteria) this;
        }

        public Criteria andSupplierTypeNotBetween(String value1, String value2) {
            addCriterion("supplier_type not between", value1, value2, "supplierType");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table oim_supplier
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table oim_supplier
     *
     * @mbggenerated do_not_delete_during_merge Tue Apr 26 13:59:10 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}