package com.dzmsoft.oim.base.pojo;

import java.util.Date;

public class OimSupplier {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column oim_supplier.id
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    private String id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column oim_supplier.name
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    private String name;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column oim_supplier.chief
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    private String chief;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column oim_supplier.chief_phone
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    private String chiefPhone;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column oim_supplier.join_date
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    private Date joinDate;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column oim_supplier.reg_province
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    private String regProvince;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column oim_supplier.short_name
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    private String shortName;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column oim_supplier.logo_pic
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    private String logoPic;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column oim_supplier.description
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    private String description;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column oim_supplier.ucs_id
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    private String ucsId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column oim_supplier.reg_city
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    private String regCity;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column oim_supplier.reg_district
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    private String regDistrict;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column oim_supplier.supplier_type
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    private String supplierType;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column oim_supplier.status
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column oim_supplier.id
     * @return  the value of oim_supplier.id
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column oim_supplier.id
     * @param id  the value for oim_supplier.id
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column oim_supplier.name
     * @return  the value of oim_supplier.name
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column oim_supplier.name
     * @param name  the value for oim_supplier.name
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column oim_supplier.chief
     * @return  the value of oim_supplier.chief
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    public String getChief() {
        return chief;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column oim_supplier.chief
     * @param chief  the value for oim_supplier.chief
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    public void setChief(String chief) {
        this.chief = chief == null ? null : chief.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column oim_supplier.chief_phone
     * @return  the value of oim_supplier.chief_phone
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    public String getChiefPhone() {
        return chiefPhone;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column oim_supplier.chief_phone
     * @param chiefPhone  the value for oim_supplier.chief_phone
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    public void setChiefPhone(String chiefPhone) {
        this.chiefPhone = chiefPhone == null ? null : chiefPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column oim_supplier.join_date
     * @return  the value of oim_supplier.join_date
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    public Date getJoinDate() {
        return joinDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column oim_supplier.join_date
     * @param joinDate  the value for oim_supplier.join_date
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    public void setJoinDate(Date joinDate) {
        this.joinDate = joinDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column oim_supplier.reg_province
     * @return  the value of oim_supplier.reg_province
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    public String getRegProvince() {
        return regProvince;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column oim_supplier.reg_province
     * @param regProvince  the value for oim_supplier.reg_province
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    public void setRegProvince(String regProvince) {
        this.regProvince = regProvince == null ? null : regProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column oim_supplier.short_name
     * @return  the value of oim_supplier.short_name
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column oim_supplier.short_name
     * @param shortName  the value for oim_supplier.short_name
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    public void setShortName(String shortName) {
        this.shortName = shortName == null ? null : shortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column oim_supplier.logo_pic
     * @return  the value of oim_supplier.logo_pic
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    public String getLogoPic() {
        return logoPic;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column oim_supplier.logo_pic
     * @param logoPic  the value for oim_supplier.logo_pic
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    public void setLogoPic(String logoPic) {
        this.logoPic = logoPic == null ? null : logoPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column oim_supplier.description
     * @return  the value of oim_supplier.description
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column oim_supplier.description
     * @param description  the value for oim_supplier.description
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column oim_supplier.ucs_id
     * @return  the value of oim_supplier.ucs_id
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    public String getUcsId() {
        return ucsId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column oim_supplier.ucs_id
     * @param ucsId  the value for oim_supplier.ucs_id
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    public void setUcsId(String ucsId) {
        this.ucsId = ucsId == null ? null : ucsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column oim_supplier.reg_city
     * @return  the value of oim_supplier.reg_city
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    public String getRegCity() {
        return regCity;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column oim_supplier.reg_city
     * @param regCity  the value for oim_supplier.reg_city
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    public void setRegCity(String regCity) {
        this.regCity = regCity == null ? null : regCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column oim_supplier.reg_district
     * @return  the value of oim_supplier.reg_district
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    public String getRegDistrict() {
        return regDistrict;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column oim_supplier.reg_district
     * @param regDistrict  the value for oim_supplier.reg_district
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    public void setRegDistrict(String regDistrict) {
        this.regDistrict = regDistrict == null ? null : regDistrict.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column oim_supplier.supplier_type
     * @return  the value of oim_supplier.supplier_type
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    public String getSupplierType() {
        return supplierType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column oim_supplier.supplier_type
     * @param supplierType  the value for oim_supplier.supplier_type
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    public void setSupplierType(String supplierType) {
        this.supplierType = supplierType == null ? null : supplierType.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column oim_supplier.status
     * @return  the value of oim_supplier.status
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column oim_supplier.status
     * @param status  the value for oim_supplier.status
     * @mbggenerated  Wed Apr 27 11:53:28 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}